# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  database: expomobi_expomobi_mc
  host: localhost
  username: expomobi_admin
  password: emobilej2011

test:
  adapter: mysql2
  database: expomobi_expomobi_mc
  host: localhost
  username: expomobi_admin
  password: emobilej2011

local:
  adapter: mysql2
  database: expomobi_expomobi_mc
  host: localhost
  username: expomobi_admin
  password: emobilej2011

production:
  adapter: mysql2
  database: expomobi_expomobi_mc
  host: localhost
  username: expomobi_admin
  password: emobilej2011